---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: topolvm-system
spec:
  replicas: 1
  template:
    spec:
      securityContext: null
      nodeSelector:
        kubernetes.io/hostname: kind-worker

      containers:
        - name: topolvm-controller
          image: topolvm:dev
          imagePullPolicy: Never
          command:
            - /topolvm-controller
            - --cert-dir=/certs
            - --stale-period=5s
            - --cleanup-interval=10s
            - --default-vg=$(DEFAULT_VG)

        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.5.0
          imagePullPolicy: "IfNotPresent"

        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.1.1
          imagePullPolicy: "IfNotPresent"

        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:v0.4.0
          imagePullPolicy: "IfNotPresent"

        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v2.0.0
          imagePullPolicy: "IfNotPresent"

      volumes:
        - name: socket-dir
          emptyDir: null
          hostPath:
            path: /var/lib/kubelet/plugins/topolvm.cybozu.com/controller
            type: DirectoryOrCreate
