kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: host-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-immediate
provisioner: topolvm.cybozu.com
volumeBindingMode: Immediate
parameters:
  "topolvm.io/volume-group": "myvg1"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner2
provisioner: topolvm.cybozu.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  "topolvm.io/volume-group": "myvg2"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner3
provisioner: topolvm.cybozu.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  "topolvm.io/volume-group": "myvg3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: host-local
  local:
    path: /tmp/e2etest1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - kind-control-plane
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: host-local
  local:
    path: /tmp/e2etest2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - kind-control-plane
